import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { prisma } from "@/lib/prisma";
import { redirect } from "next/navigation";
import Link from "next/link";
import { FaArrowLeft, FaListAlt, FaPlusCircle } from "react-icons/fa";
import RondasTabla from "../components/RondasTabla";
const TAKE = 20;
export default async function MisRondas({ searchParams }: { searchParams: Promise<{ page?: string }> }) { const session = await getServerSession(authOptions); if (!session?.user) redirect('/login'); if (!['MEDICO_RONDA', 'TECNICO', 'ADMINISTRATIVO'].includes(session.user.rol)) redirect('/'); const p = await searchParams; const requested = Math.max(1, Number(p.page) || 1); const where = { usuarioId: session.user.id }; const total = await prisma.rondaIntramural.count({ where }); const pages = Math.max(1, Math.ceil(total / TAKE)); const page = Math.min(requested, pages); const rondas = await prisma.rondaIntramural.findMany({ where, include: { medicamentos: { orderBy: { orden: 'asc' } } }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * TAKE, take: TAKE }); return <div className="min-h-screen bg-gradient-to-b from-red-50 to-white"><div className="container mx-auto px-4 py-7"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/rondas" className="rounded-xl border border-slate-200 bg-white p-3 hover:bg-slate-50"><FaArrowLeft /></Link><div><h1 className="text-2xl font-extrabold text-slate-900"><FaListAlt className="mr-2 inline text-red-700" />Mis pacientes reportados</h1><p className="text-sm text-slate-500">Esta vista solo contiene los reportes creados con tu perfil.</p></div></div><Link href="/rondas/registrar" className="inline-flex items-center gap-2 rounded-xl bg-red-700 px-4 py-3 font-bold text-white hover:bg-red-800"><FaPlusCircle /> Registrar paciente</Link></div><RondasTabla rondas={rondas} page={page} totalPages={pages} basePath="/rondas/mis" /></div></div>; }
