"use client";

import { useState } from "react";
import { FaCalendarAlt, FaChevronLeft, FaChevronRight, FaTimes } from "react-icons/fa";

const etiqueta: Record<string, string> = { MILIGRAMOS: "Miligramos", GRAMOS: "Gramos", UNIDADES: "Unidades", GOTAS: "Gotas", MILILITROS: "Mililitros", INTRAVENOSA: "Intravenosa", INTRAMUSCULAR: "Intramuscular", SUBCUTANEA: "Subcutánea", NEBULIZADA: "Nebulizada", ORAL: "Oral", INFUSION_CONTINUA: "Infusión continua", CADA_4_HORAS: "Cada 4 horas", CADA_6_HORAS: "Cada 6 horas", CADA_8_HORAS: "Cada 8 horas", CADA_12_HORAS: "Cada 12 horas", CADA_24_HORAS: "Cada 24 horas", CADA_48_HORAS: "Cada 48 horas", CADA_72_HORAS: "Cada 72 horas", NO_APLICA: "No aplica" };
type MedicamentoRonda = { id: string; nombre: string; dosis: string; medida: string; viaAdministracion: string; frecuencia: string; dias: number };
type Reportante = { nombres: string; primerApellido: string; segundoApellido: string | null };
type Ronda = { id: string; pacienteNombre: string; pacienteTipoDoc: string; pacienteDocumento: string; eps: string; cie10Codigo: string; diagnosticoDescriptivo: string; otros: string | null; createdAt: Date | string; medicamentos: MedicamentoRonda[]; usuario?: Reportante };
function fecha(value: string | Date) { return new Intl.DateTimeFormat("es-CO", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Bogota" }).format(new Date(value)); }
function nombreReporte(ronda: Ronda) { const u = ronda.usuario; return u ? `${u.nombres} ${u.primerApellido}${u.segundoApellido ? ` ${u.segundoApellido}` : ""}`.replace(/\s+/g, " ") : "Mi reporte"; }

export default function RondasTabla({ rondas, page, totalPages, basePath, mostrarReportante = false }: { rondas: Ronda[]; page: number; totalPages: number; basePath: string; mostrarReportante?: boolean }) {
  const [seleccionada, setSeleccionada] = useState<Ronda | null>(null);
  const ir = (next: number) => { const join = basePath.includes("?") ? "&" : "?"; window.location.href = `${basePath}${join}page=${next}`; };
  return <><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
    {rondas.length === 0 ? <div className="p-12 text-center text-slate-500">No hay pacientes reportados con los filtros seleccionados.</div> : <><div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead className="bg-slate-50 text-left text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-4">Paciente</th><th className="px-5 py-4">Identificación</th><th className="px-5 py-4">EPS</th><th className="px-5 py-4">Diagnóstico</th>{mostrarReportante && <th className="px-5 py-4">Reportado por</th>}<th className="px-5 py-4">Fecha</th></tr></thead><tbody className="divide-y divide-slate-100">{rondas.map((ronda) => <tr key={ronda.id} onClick={() => setSeleccionada(ronda)} className="cursor-pointer transition-colors hover:bg-red-50"><td className="px-5 py-4"><p className="font-bold text-slate-800">{ronda.pacienteNombre}</p><p className="text-xs text-red-700">Ver detalle</p></td><td className="px-5 py-4 text-sm text-slate-600">{ronda.pacienteTipoDoc} {ronda.pacienteDocumento}</td><td className="px-5 py-4 text-sm text-slate-600">{ronda.eps}</td><td className="px-5 py-4"><span className="font-semibold text-slate-700">{ronda.cie10Codigo}</span><p className="max-w-xs truncate text-xs text-slate-500">{ronda.diagnosticoDescriptivo}</p></td>{mostrarReportante && <td className="px-5 py-4 text-sm text-slate-600">{nombreReporte(ronda)}</td>}<td className="px-5 py-4 text-sm text-slate-600">{fecha(ronda.createdAt)}</td></tr>)}</tbody></table></div>
      <div className="flex items-center justify-between border-t border-slate-100 px-5 py-3 text-sm"><span className="text-slate-500">Página {page} de {totalPages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => ir(page - 1)} className="rounded-lg border border-slate-200 p-2 disabled:opacity-40"><FaChevronLeft /></button><button disabled={page >= totalPages} onClick={() => ir(page + 1)} className="rounded-lg border border-slate-200 p-2 disabled:opacity-40"><FaChevronRight /></button></div></div></>}
  </div>{seleccionada && <Detalle ronda={seleccionada} reportante={mostrarReportante ? nombreReporte(seleccionada) : undefined} onClose={() => setSeleccionada(null)} />}</>;
}
function Detalle({ ronda, reportante, onClose }: { ronda: Ronda; reportante?: string; onClose: () => void }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/50 p-4" onMouseDown={onClose}><div role="dialog" aria-modal="true" aria-label="Detalle de ronda" className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white shadow-2xl" onMouseDown={(e) => e.stopPropagation()}><div className="sticky top-0 flex items-start justify-between border-b border-slate-100 bg-white p-5"><div><p className="text-sm font-bold uppercase tracking-wide text-red-700">Ronda Intramural</p><h2 className="text-xl font-extrabold text-slate-900">{ronda.pacienteNombre}</h2><p className="text-sm text-slate-500"><FaCalendarAlt className="inline mr-1" />{fecha(ronda.createdAt)}</p></div><button onClick={onClose} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100" aria-label="Cerrar"><FaTimes /></button></div><div className="space-y-6 p-5"><div className="grid grid-cols-1 gap-4 md:grid-cols-3"><Dato label="Identificación" value={`${ronda.pacienteTipoDoc} ${ronda.pacienteDocumento}`} /><Dato label="EPS" value={ronda.eps} /><Dato label="Reportado por" value={reportante || "Mi perfil"} /><Dato label="Código CIE-10" value={ronda.cie10Codigo} /><div className="md:col-span-2"><Dato label="Diagnóstico descriptivo" value={ronda.diagnosticoDescriptivo} /></div></div><div><h3 className="mb-3 text-base font-extrabold text-slate-800">Medicamentos ordenados</h3><div className="overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[600px] text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-500"><tr><th className="p-3">Medicamento</th><th className="p-3">Dosis</th><th className="p-3">Medida</th><th className="p-3">Vía</th><th className="p-3">Frecuencia</th><th className="p-3">Días</th></tr></thead><tbody className="divide-y divide-slate-100">{ronda.medicamentos.map((m) => <tr key={m.id}><td className="p-3 font-semibold text-slate-700">{m.nombre}</td><td className="p-3">{m.dosis}</td><td className="p-3">{etiqueta[m.medida] ?? m.medida}</td><td className="p-3">{etiqueta[m.viaAdministracion] ?? m.viaAdministracion}</td><td className="p-3">{etiqueta[m.frecuencia] ?? m.frecuencia}</td><td className="p-3">{m.dias}</td></tr>)}</tbody></table></div></div><Dato label="Otros" value={ronda.otros || "No aplica"} /></div></div></div>; }
function Dato({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm text-slate-800">{value}</p></div>; }
