-- AlterEnum
ALTER TYPE "TipoNovedadPaciente" ADD VALUE IF NOT EXISTS 'ALTA_TARDIA';
ALTER TYPE "TipoNovedadPaciente" ADD VALUE IF NOT EXISTS 'RETRASO_INICIO_TRATAMIENTO';
ALTER TYPE "TipoNovedadPaciente" ADD VALUE IF NOT EXISTS 'OTRA';
