import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { prisma } from "@/lib/prisma";
import { Prisma } from "@prisma/client";
import { redirect } from "next/navigation";
import Link from "next/link";
import { FaArrowLeft, FaUsers } from "react-icons/fa";
import RondasTabla from "../components/RondasTabla";
import RondasFiltros from "./RondasFiltros";
const TAKE = 20;
const val = (v: string | string[] | undefined) => Array.isArray(v) ? (v[0] ?? '') : (v ?? '');
const nombre = (u: { nombres: string; primerApellido: string; segundoApellido: string | null }) => `${u.nombres} ${u.primerApellido} ${u.segundoApellido ?? ''}`.replace(/\s+/g, ' ').trim();
export default async function TodasRondas({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const session = await getServerSession(authOptions); if (!session?.user) redirect('/login'); if (!['ADMINISTRATIVO', 'TECNICO'].includes(session.user.rol)) redirect('/'); const sp = await searchParams; const initial = { usuarioId: val(sp.usuarioId), eps: val(sp.eps), desde: val(sp.desde), hasta: val(sp.hasta), q: val(sp.q) }; const pageRequested = Math.max(1, Number(val(sp.page)) || 1); const where: Prisma.RondaIntramuralWhereInput = {}; if (initial.usuarioId) where.usuarioId = initial.usuarioId; if (initial.eps) where.eps = { contains: initial.eps, mode: 'insensitive' }; if (initial.q) where.OR = [{ pacienteNombre: { contains: initial.q, mode: 'insensitive' } }, { pacienteDocumento: { contains: initial.q, mode: 'insensitive' } }]; if (initial.desde || initial.hasta) { where.createdAt = {}; if (initial.desde) where.createdAt.gte = new Date(`${initial.desde}T00:00:00-05:00`); if (initial.hasta) where.createdAt.lte = new Date(`${initial.hasta}T23:59:59.999-05:00`); } const total = await prisma.rondaIntramural.count({ where }); const totalPages = Math.max(1, Math.ceil(total / TAKE)); const page = Math.min(pageRequested, totalPages); const [rondas, usuarios] = await Promise.all([prisma.rondaIntramural.findMany({ where, include: { medicamentos: { orderBy: { orden: 'asc' } }, usuario: { select: { nombres: true, primerApellido: true, segundoApellido: true } } }, orderBy: { createdAt: 'desc' }, skip: (page - 1) * TAKE, take: TAKE }), prisma.user.findMany({ where: { rondas: { some: {} } }, select: { id: true, nombres: true, primerApellido: true, segundoApellido: true }, orderBy: [{ nombres: 'asc' }, { primerApellido: 'asc' }] })]); const p = new URLSearchParams(); Object.entries(initial).forEach(([k, v]) => { if (v) p.set(k, v); }); const basePath = `/rondas/todas${p.size ? `?${p}` : ''}`; return <div className="min-h-screen bg-gradient-to-b from-red-50 to-white"><div className="container mx-auto px-4 py-7"><div className="mb-5 flex items-center gap-3"><Link href="/rondas" className="rounded-xl border border-slate-200 bg-white p-3 hover:bg-slate-50"><FaArrowLeft /></Link><div><h1 className="text-2xl font-extrabold text-slate-900"><FaUsers className="mr-2 inline text-red-700" />Todos los pacientes reportados</h1><p className="text-sm text-slate-500">Panel administrativo de Ronda Intramural.</p></div></div><RondasFiltros initial={initial} reportadores={usuarios.map((u) => ({ id: u.id, nombre: nombre(u) }))} /><p className="mb-3 text-sm text-slate-500">{total} paciente{total === 1 ? '' : 's'} encontrado{total === 1 ? '' : 's'}.</p><RondasTabla rondas={rondas} page={page} totalPages={totalPages} basePath={basePath} mostrarReportante /></div></div>; }
